version: "3.7"

services:
  bb-app:
    image: tahirbaltee/getting-started:latest  # Corrected image reference
    deploy:
      mode: replicated
      replicas: 3  # Ensures 3 replicas
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - "node.platform.os == linux"  # Runs on Linux nodes
    ports:
      - "8000:3000"  # Exposing container port to host
    networks:
      - bb-network

networks:
  bb-network:
    driver: overlay  # Ensures it runs in Swarm mode
