version: "3.7"

services:
  bb-app:
    image: tahirbaltee/my-app-image:latest  # Full Docker Hub image reference
    deploy:
      mode: replicated
      replicas: 3  # Ensures 3 replicas
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - "node.platform.os == linux"  # Ensure it runs only on Linux nodes
    ports:
      - "8000:3000"  # Ensures external access
    networks:
      - bb-network  # Attach to Swarm overlay network

networks:
  bb-network:
    driver: overlay  # Required for Docker Swarm
