version: "3.7"

services:
  bb-app:
    image: getting-started
    ports:
      - "8000:3000"
    deploy:
      replicas: 3  # Create 3 replicas of the service
      update_config:
        parallelism: 1  # Update 1 replica at a time
        delay: 10s      # Wait 10 seconds between updates
      restart_policy:
        condition: on-failure  # Restart the container if it fails
      placement:
        constraints:
          - "node.role==worker"  # Optional: Only deploy on worker nodes